name: John Burton-Race
markdown: redcarpet
markdown_ext: markdown,mkd,mkdn,md
pygments: false
include: ['.htaccess', '_']
exclude: ['node_modules', 'config.rb', 'package.json', 'README.md', '_assets', 'Gruntfile.js']
